from cvplayer.core.media_player.video_player_core.interface.media_buttons import PlayPauseButton, PreviousFrameButton, NextFrameButton
from cvplayer.core.media_player.video_player_core.interface.video_speed_button import VideoSpeedButton
from cvplayer.core.media_player.video_player_core.interface.slider import VideoSlider
from cvplayer.core.media_player.video_player_core.interface.viewer import ImageViewer
from cvplayer.core.media_player.video_player_core.interface.print_screen_button import PrintScreenButton
from cvplayer.core.media_player.video_player_core.interface.video_time_counter import TimeCounter
from cvplayer.core.media_player.video_player_core.interface.videos_list import VideosList
from cvplayer.core.media_player.video_player_core.interface.add_videos_button import AddVideosButton